# Generated by Django 4.2.4 on 2023-10-09 19:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionCuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('moderada', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('E', 'En Edicion'), ('R', 'En Revisión'), ('P', 'Publicado'), ('r', 'Rechazado'), ('I', 'Inactivo')], default='B', max_length=1)),
                ('titulo', models.CharField(max_length=255)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contenido_imagenes/')),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('razon', models.CharField(blank=True, null=True)),
                ('ultimo_editor', models.CharField(blank=True, max_length=255)),
                ('ultimo_publicador', models.CharField(blank=True, max_length=255)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('autor', models.ForeignKey(limit_choices_to={'roles__nombre': 'Autor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_autor', to='GestionCuentas.usuariorol')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('editor', models.ForeignKey(limit_choices_to={'roles__nombre': 'Editor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_editor', to='GestionCuentas.usuariorol')),
                ('publicador', models.ForeignKey(limit_choices_to={'roles__nombre': 'Publicador'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_publicador', to='GestionCuentas.usuariorol')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contenido')),
            ],
        ),
    ]
