# Generated by Django 4.2.4 on 2023-11-01 02:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionCuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('moderada', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('E', 'En Edicion'), ('R', 'En Revisión'), ('P', 'Publicado'), ('r', 'Rechazado'), ('I', 'Inactivo')], default='B', max_length=1)),
                ('titulo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('resumen', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contenido_imagenes/')),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('razon', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ultimo_editor', models.CharField(blank=True, max_length=255)),
                ('ultimo_publicador', models.CharField(blank=True, max_length=255)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('promedio_calificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('autor', models.ForeignKey(limit_choices_to={'roles__nombre': 'Autor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_autor', to='GestionCuentas.usuariorol')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('editor', models.ForeignKey(limit_choices_to={'roles__nombre': 'Editor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_editor', to='GestionCuentas.usuariorol')),
                ('publicador', models.ForeignKey(limit_choices_to={'roles__nombre': 'Publicador'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_publicador', to='GestionCuentas.usuariorol')),
            ],
        ),
        migrations.CreateModel(
            name='VersionesContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField()),
                ('fecha_version', models.DateTimeField(auto_now_add=True)),
                ('titulo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('resumen', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contenido_imagenes/')),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('razon', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('contenido_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contenido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
