# Generated by Django 4.2.4 on 2023-09-03 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0009_alter_permisosper_options'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='titulo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contenido',
            name='autor',
            field=models.ForeignKey(limit_choices_to={'roles__nombre': 'Autor'}, on_delete=django.db.models.deletion.CASCADE, to='GestionCuentas.usuariorol'),
        ),
    ]
