# Generated by Django 4.2.4 on 2023-09-05 20:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0009_alter_permisosper_options'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('autor', models.ForeignKey(limit_choices_to={'roles__nombre': 'Autor'}, on_delete=django.db.models.deletion.CASCADE, to='GestionCuentas.usuariorol')),
            ],
        ),
    ]
