# Generated by Django 4.2.5 on 2023-09-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('R', 'En Revisión'), ('P', 'Publicado'), ('R', 'Rechazado'), ('I', 'Inactivo')], default='B', max_length=1),
        ),
    ]
