# Generated by Django 4.2.4 on 2023-11-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='veces_compartido',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
