# Generated by Django 4.2.4 on 2023-09-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='resumen',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
