# Generated by Django 4.2.5 on 2023-09-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contenido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('E', 'En Edicion'), ('R', 'En Revisión'), ('P', 'Publicado'), ('R', 'Rechazado'), ('I', 'Inactivo')], default='R', max_length=1),
        ),
    ]
