# Generated by Django 4.2.4 on 2023-11-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contenido_veces_compartido'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='veces_visto',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
