# Generated by Django 4.2.4 on 2023-09-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contenido_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='contenido_imagenes/'),
        ),
    ]
