# Generated by Django 4.2.4 on 2023-11-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_likes'),
        ('core', '0003_contenido_veces_visto'),
    ]

    operations = [
    ]
