# Generated by Django 4.2.4 on 2023-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contenido_razon_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='razon_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
