# Generated by Django 4.2.5 on 2023-09-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contenido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('E', 'En Edicion'), ('R', 'En Revisión'), ('P', 'Publicado'), ('r', 'Rechazado'), ('I', 'Inactivo')], default='B', max_length=1),
        ),
    ]
