# Generated by Django 4.2.4 on 2023-09-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contenido_razon_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='razon_rechazo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
