# Generated by Django 4.2.4 on 2023-09-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contenido_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
