# Generated by Django 4.2.4 on 2023-11-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_0002_likes_0003_contenido_veces_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='destacado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
