# Generated by Django 4.2.4 on 2023-09-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contenido_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='files/resumen'),
        ),
    ]
