# Generated by Django 4.2.4 on 2023-11-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0006_remove_usuariorol_categorias_favoritas'),
        ('core', '0005_contenido_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='core.categoria')),
                ('user_sub', models.ManyToManyField(related_name='user_sub', to='GestionCuentas.usuariorol')),
            ],
        ),
    ]
