# Generated by Django 4.2.4 on 2023-10-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contenido_razon_rechazo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='razon_rechazo',
            new_name='razon',
        ),
        migrations.AddField(
            model_name='contenido',
            name='ultimo_editor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
