# Generated by Django 4.2.4 on 2023-11-28 19:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='titulo_abreviado',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
