# Generated by Django 4.2.4 on 2023-10-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reaccion_remove_like_contenido_remove_like_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaccion',
        ),
    ]
