# Generated by Django 4.2.4 on 2023-10-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_razon_rechazo_contenido_razon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='ultimo_publicador',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
