# Generated by Django 4.2.4 on 2023-11-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0006_remove_usuariorol_categorias_favoritas'),
        ('core', '0007_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCuentas.usuariorol'),
        ),
    ]
