# Generated by Django 4.2.4 on 2023-10-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0002_alter_permisosper_options'),
        ('core', '0007_contenido_ultimo_publicador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCuentas.usuariorol'),
        ),
    ]
