# Generated by Django 4.2.4 on 2023-10-15 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_delete_reaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='me_gusta_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contenido',
            name='no_me_gusta_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='me_gusta',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='no_me_gusta',
        ),
        migrations.AddField(
            model_name='contenido',
            name='me_gusta',
            field=models.ManyToManyField(blank=True, related_name='contenidos_me_gusta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contenido',
            name='no_me_gusta',
            field=models.ManyToManyField(blank=True, related_name='contenidos_no_me_gusta', to=settings.AUTH_USER_MODEL),
        ),
    ]
