# Generated by Django 4.2.4 on 2023-10-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contenido_ultimo_publicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
