# Generated by Django 4.2.4 on 2023-10-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contenido_me_gusta_count_contenido_no_me_gusta_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='compartido',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='me_gusta',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='me_gusta_count',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='no_me_gusta',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='no_me_gusta_count',
        ),
    ]
