# Generated by Django 4.2.4 on 2023-10-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0001_initial'),
        ('core', '0008_contenido_editor_contenido_publicador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='autor',
            field=models.ForeignKey(limit_choices_to={'roles__nombre': 'Autor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_autor', to='GestionCuentas.usuariorol'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='editor',
            field=models.ForeignKey(limit_choices_to={'roles__nombre': 'Editor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_editor', to='GestionCuentas.usuariorol'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='publicador',
            field=models.ForeignKey(limit_choices_to={'roles__nombre': 'Publicador'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_publicador', to='GestionCuentas.usuariorol'),
        ),
    ]
