# Generated by Django 4.2.4 on 2023-11-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contenido_titulo_abreviado'),
        ('core', '0009_alter_contenido_fecha_publicacion'),
    ]

    operations = [
    ]
