# Generated by Django 4.2.4 on 2023-10-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contenido_autor_alter_contenido_editor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='publicador',
        ),
    ]
