# Generated by Django 4.2.4 on 2023-11-29 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0007_rol_borrado'),
        ('core', '0010_merge_20231128_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='autor',
            field=models.ForeignKey(limit_choices_to={'roles__permisos__codename': 'Vista_autor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_autor', to='GestionCuentas.usuariorol'),
        ),
    ]
