# Generated by Django 4.2.4 on 2023-10-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0001_initial'),
        ('core', '0010_remove_contenido_editor_remove_contenido_publicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='editor',
            field=models.ForeignKey(limit_choices_to={'roles__nombre': 'Editor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_editor', to='GestionCuentas.usuariorol'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='publicador',
            field=models.ForeignKey(limit_choices_to={'roles__nombre': 'Publicador'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_publicador', to='GestionCuentas.usuariorol'),
        ),
    ]
