# Generated by Django 4.2.4 on 2023-10-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contenido_editor_contenido_publicador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
