# Generated by Django 4.2.4 on 2023-10-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contenido_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='titulo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
