# Generated by Django 4.2.4 on 2023-10-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_contenido_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
