# Generated by Django 4.2.4 on 2023-10-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_historialcontenido'),
        ('core', '0014_alter_contenido_titulo'),
    ]

    operations = [
    ]
