# Generated by Django 4.2.4 on 2023-10-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contenido_autor'),
        ('core', '0015_merge_20231007_2005'),
    ]

    operations = [
    ]
