# Generated by Django 4.2.4 on 2023-10-09 14:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0003_alter_permisosper_options'),
        ('core', '0016_merge_20231009_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='autor',
            field=models.ForeignKey(limit_choices_to={'roles__nombre': 'Autor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_autor', to='GestionCuentas.usuariorol'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='resumen',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
