# Generated by Django 4.2.4 on 2023-10-09 15:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_contenido_autor_alter_contenido_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='razon',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='titulo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
