# Generated by Django 4.2.4 on 2023-10-12 13:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_contenido_razon_alter_contenido_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionesContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField()),
                ('fecha_version', models.DateTimeField(auto_now_add=True)),
                ('titulo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('resumen', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contenido_imagenes/')),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('razon', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('contenido_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contenido')),
            ],
        ),
    ]
