# Generated by Django 3.2.12 on 2023-08-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosPer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('Boton desarrollador', 'Permite entrar a la vista desarrollador'), ('Vista autor', 'Permite ingresar a la vista autor')],
            },
        ),
    ]
