# Generated by Django 4.2.4 on 2023-11-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contenido_destacado'),
        ('GestionCuentas', '0002_alter_permisosper_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorol',
            name='categorias_favoritas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_favoritos', to='core.categoria'),
        ),
    ]
