# Generated by Django 3.2.12 on 2023-08-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0002_permisosper'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(default=None, to='GestionCuentas.PermisosPer'),
        ),
    ]
