# Generated by Django 3.2.12 on 2023-08-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('GestionCuentas', '0003_rol_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(default=None, to='auth.Permission'),
        ),
    ]
