# Generated by Django 3.2.12 on 2023-08-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0004_alter_rol_permisos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisosper',
            options={'permissions': [('Boton desarrollador', 'Permite entrar a la vista desarrollador'), ('Vista autor', 'Permite ingresar a la vista autor'), ('Vista editor', 'Permite ingresar a la vista editor')]},
        ),
    ]
