# Generated by Django 4.2.4 on 2023-11-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contenido_destacado'),
        ('GestionCuentas', '0004_remove_usuariorol_categorias_favoritas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorol',
            name='categorias_favoritas',
            field=models.ManyToManyField(blank=True, to='core.categoria'),
        ),
    ]
