# Generated by Django 4.2.4 on 2023-11-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0005_usuariorol_categorias_favoritas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariorol',
            name='categorias_favoritas',
        ),
    ]
