# Generated by Django 4.2.4 on 2023-11-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0006_remove_usuariorol_categorias_favoritas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='borrado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
