# Generated by Django 3.2.12 on 2023-08-27 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0007_remove_usuariorol_user_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisosper',
            options={'permissions': [('Boton desarrollador', 'Permite entrar a la vista desarrollador'), ('Vista autor', 'Permite ingresar a la vista autor'), ('Vista editor', 'Permite ingresar a la vista editor'), ('Vista pubicador', 'Permite ingresar a la vista publicador'), ('Vista administrador', 'Permite ingresar a la vista administrador')]},
        ),
    ]
