# Generated by Django 3.2.12 on 2023-08-28 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCuentas', '0008_alter_permisosper_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisosper',
            options={'permissions': [('Boton desarrollador', 'Permite entrar a la vista desarrollador'), ('Vista autor', 'Permite ingresar a la vista autor'), ('Vista editor', 'Permite ingresar a la vista editor'), ('Vista publicador', 'Permite ingresar a la vista publicador'), ('Vista administrador', 'Permite ingresar a la vista administrador')]},
        ),
    ]
